package game.data.chunk.entity;

import com.google.gson.Gson;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.HashMap;

/**
 * Holds a global palette as introduced in 1.13. These are read from a simple JSON file that is generated by the
 * Minecraft server.jar. More details are in the readme file in the resource folder.
 */
public class EntityNames {
    private HashMap<Integer, String> entities;

    public EntityNames() {
        entities = new HashMap<>();
    }

    /**
     * Instantiate a global palette using the given Minecraft version.
     * @param version the Minecraft version, NOT protocol version
     */
    public static EntityNames fromJson(String version) {
        String file = "entities-" + version + ".json";
        InputStream input = EntityNames.class.getClassLoader().getResourceAsStream(file);

        // if the file doesn't exist, there is no palette for this version.
        if (input == null) { return new EntityNames(); }

        return new Gson().fromJson(new InputStreamReader(input), EntityNames.class);
    }

    /**
     * Get a block state from a given index. Used to convert packet palettes to the global palette.
     */
    public String getName(int key) {
        return entities.getOrDefault(key, null);
    }
}
