package game.data.chunk.palette;

import com.google.gson.Gson;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.HashMap;

/**
 * Holds a global palette as introduced in 1.13. These are read from a simple JSON file that is generated by the
 * Minecraft server.jar. More details are in the readme file in the resource folder.
 */
public class GlobalPalette {
    private HashMap<Integer, BlockState> states;

    /**
     * Instantiate a global palette using the given Minecraft version.
     * @param version the Minecraft version, NOT protocol version
     */
    public GlobalPalette(String version) {
        this.states = new HashMap<>();

        String file = "blocks-" + version + ".json";
        InputStream input = GlobalPalette.class.getClassLoader().getResourceAsStream(file);

        // if the file doesn't exist, there is no palette for this version.
        if (input == null) { return; }

        JsonResult map = new Gson().fromJson(new InputStreamReader(input), JsonResult.class);
        map.forEach((name, type) -> type.states.forEach(state -> {
            states.put(state.id, new BlockState(name, state.properties));
        }));
    }

    /**
     * Get a block state from a given index. Used to convert packet palettes to the global palette.
     */
    public BlockState getState(int key) {
        return states.getOrDefault(key, null);
    }

}

// we need a class to represent this type because of type erasure nonsense, otherwise Gson will get angry over casting.
class JsonResult extends HashMap<String, JsonBlockType> { }
